# Diccionario de mensajes en diferentes idiomas
mensajes = {
    "es": {
        "bienvenido": "¡Bienvenido!",
        "error": "¡Error! Algo salió mal.",
        "teseract_instalado": "Tesseract-OCR está instalado.",
        "teseract_no_instalado": "Tesseract-OCR no está instalado. Se procederá con la instalación.",
        "teseract_error": "Hubo un error al instalar Tesseract-OCR.",
        "quitar_item_text": "Quitar",
        "texto_susurros": "Susurros",
        "info_text_robar": "He quitado un objeto",
        "abrir_bolsa": "Abrimos bolsa",
        "info_meowth": "Soy un meowth",
        "texto_cacheo": "Cacheo",
        "texto_comenzar_pescar": "Intento pescar",
        "texto_a_picado_un_pkm": "Ha Picado Un",
        "texto_no_ha_picado_pkm": "No pescan",
        "magikarp_no_capturado": "No se ha capturado",
        "magikarp_capturado": "Se Ha capturado",
        "inicio_de_pesca_magikarp": "Comenzando cazar magikarps",
        "inicio_de_ladron_luvdisc": "Comenzando a cazar luvdisc usando ladron",
        "luvdisc_encontrado": "Es un Luvdisc",
        "corsola_encontrado": "Es un Corsola",
        "texto_atacamos": "Atacamos",
        "inicio_de_cacheo_luvdisc": "Comenzando a cazar luvdisc usando cacheo",
        "texto_tiene_item_luvdisc": "Escama Encontrada",
        "texto_escapar": "Escapamos",
        "texto_esc_corazon": "Escamas: ",
        "inicio_de_ladron_cacheo_luvdisc": "Dia de pago + Ladron Teselia Bahia Arenisca",
        "Shellder_encontrado": "Es un Shellder",
        "texto_atacamos_otravez": "Atacamos de nuevo",
        "texto_usos_de_baya_zanama": "Falta para usar la Baya {FaltaParaMarchar}",
        "texto_apagar_pc": "Falta para apagar el pc {FaltaParaApagar}",
        "inicio_de_dia_de_pago_teselia": "Dia de pago Teselia Torreduodraco",
        "texto_parar_bot": "Se parara en el proximo bucle",
        "texto_username": "Usuario",
        "texto_password": "Contraseña",
        "texto_estado": "Estado",
        "texto_btn_torre_duodraco": "Torre Duodraco Teselia Dia de Pago + Zanaba",
        "texto_btn_pueblo_arenisca": "Pueblo Arenisca Teselia Dia de Pago + Ladron",
        "texto_btn_exp_tentacruel": "EXP Tentacruel Hoeen",
        "texto_btn_ladron_luvdisc": "Ladron a Luvdise",
        "texto_btn_cacheo_luvdisc": "Cacheo a Luvdise",
        "texto_btn_MonAmuleto_Kanto": "MonAmuleto Kanto Hordas Meowth",
        "texto_btn_capturar_magikarps_hoeen": "Capturar Magikarps Hoeen",
        "texto_error_texto_en_blanco": "Campos en blanco.",
        "texto_error_desactualizado": "Version antigua, actualiza a la nueva version",
        "texto_error_no_existe_cuenta": "No existe la cuenta.",
        "texto_error_error_password": "Credenciales incorrectas.",
        "texto_error_server_mantenimiento": "Mantenimiento.",
        "texto_cerar_programa_bot_on": "Error: Para el loop del bot antes de cerrar el programa",
        "capturar_shinny_mienshao": "Captuar Shinny Mienshao"
    },
    "en": {
        "bienvenido": "Welcome!",
        "error": "Error! Something went wrong.",
        "teseract_instalado": "Tesseract-OCR is installed.",
        "teseract_no_instalado": "Tesseract-OCR is not installed. Proceeding with the installation.",
        "teseract_error": "There was an error installing Tesseract-OCR.",
        "quitar_item_text": "Remove",
        "texto_susurros": "Whispers",
        "info_text_robar": "I have taken an item",
        "abrir_bolsa": "Open bag",
        "info_meowth": "I am a meowth",
        "texto_cacheo": "Frisk",
        "texto_comenzar_pescar": "Trying to fish",
        "texto_a_picado_un_pkm": "A wild",
        "texto_no_ha_picado_pkm": "No bites",
        "magikarp_no_capturado": "Not captured",
        "magikarp_capturado": "Captured",
        "inicio_de_pesca_magikarp": "Starting to catch Magikarps",
        "inicio_de_ladron_luvdisc": "Starting to catch Luvdisc using Thief",
        "luvdisc_encontrado": "It's a Luvdisc",
        "corsola_encontrado": "It's a Corsola",
        "texto_atacamos": "Attacking",
        "inicio_de_cacheo_luvdisc": "Starting to catch Luvdisc using Frisk",
        "texto_tiene_item_luvdisc": "Found a scale",
        "texto_escapar": "Escaping",
        "texto_esc_corazon": "Scales: ",
        "inicio_de_ladron_cacheo_luvdisc": "Payday + Thief Teselia Bahia Arenisca",
        "Shellder_encontrado": "It's a Shellder",
        "texto_atacamos_otravez": "Attacking again",
        "texto_usos_de_baya_zanama": "Uses remaining for the Berry {FaltaParaMarchar}",
        "texto_apagar_pc": "Time remaining to turn off PC {FaltaParaApagar}",
        "inicio_de_dia_de_pago_teselia": "Teselia Payday Tower Dragonspiral",
        "texto_parar_bot": "Will stop in the next loop",
        "texto_username": "Username",
        "texto_password": "Password",
        "texto_estado": "Status",
        "texto_btn_torre_duodraco": "Tower Dragonspiral Teselia Payday + Mago",
        "texto_btn_pueblo_arenisca": "Sandgem Town Teselia Payday + Thief",
        "texto_btn_exp_tentacruel": "Tentacruel EXP Hoeen",
        "texto_btn_ladron_luvdisc": "Thief to Luvdisc",
        "texto_btn_cacheo_luvdisc": "Frisk to Luvdisc",
        "texto_btn_MonAmuleto_Kanto": "Kanto MonAmulet Meowth Hordes",
        "texto_btn_capturar_magikarps_hoeen": "Capture Magikarps Hoeen",
        "texto_error_texto_en_blanco": "Blank fields.",
        "texto_error_desactualizado": "Old version, please update to the new version",
        "texto_error_no_existe_cuenta": "Account does not exist.",
        "texto_error_error_password": "Incorrect credentials.",
        "texto_error_server_mantenimiento": "Maintenance.",
        "texto_cerar_programa_bot_on": "Error: Please stop the bot loop before closing the program.",
        "capturar_shinny_mienshao": "Catch Shinny Mienshao"
    }
}
